import { StyleSheet } from 'react-native';

const mainColor = "#BCC6CC"

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        width: "100%",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "center",
        backgroundColor: "white",
        padding: 20,
    },
    welcome: {
        width: "90%",
        flexDirection: "column",
        backgroundColor: "rgba(188,198,204, 0.2)",
        boxShadow: "1px 1px 5px #4c787e",
        padding: 20,
        borderRadius: 20,
    },
    buttonStyle: {
        marginVertical: 10,
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        padding: 10,
        borderRadius: 15,
        borderColor: mainColor,
        borderWidth: 1,
    },
    buttonText: {
        fontSize: 18,
        fontWeight: "500",
    },
    inputStyle: {
        fontSize: 20,
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 20,
        color: "black",
        padding: 10,
        height: 50,
        marginVertical: 5,
        width: '100%',
    },
    imageBackground: {
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        height: "100%",
    },
    errorDisplay: {
        width: "100%",
        color: "red",
        fontSize: 16,
        textAlign: "center",
        borderWidth: 1,
        borderColor: "red",
        padding: 10,
        borderRadius: 15,
    },
    listItem: {
        width: "100%",
        flexDirection: "row",
        backgroundColor: "white",
        padding: 10,
        borderRadius: 10,
        justifyContent: "space-between",
        alignItems: "center",
    },
    toggle: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
        borderColor: "white",
        marginVertical: 5,
    },
    dropdown: {
        width: "100%",
    },
    vehicleRegister: {
        width: "90%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    registerInput: {
        width: "60%",
        borderWidth: 2,
        borderColor: "gray",
        height: 40,
        padding: 10,
        borderRadius: 15,
        marginVertical: 5,
    },
    textBox: {
        width: "100%",
        height: 70,
        textAlign: "left",
        textAlignVertical: "top",
        backgroundColor: "white",
        borderWidth: 3,
        borderColor: "gray",
        borderRadius: 15,
        marginVertical: 5,
        padding: 10,
    },
    mainView: {
        width: "100%",
        borderRadius: 10,
        flexDirection: 'column',
        gap: 5,
        padding: 10,
        borderWidth: 1,
        borderColor: mainColor,
    },
    subView: {
        width: "100%",
        flexDirection: "row",
        justifyContent: 'space-between',
    },
    modal: {
        flexGrow: 1,
        backgroundColor: "#eeeee4",
        height: "50%",
        marginTop: 190,
        borderColor: "gray",
        padding: 15,
        borderRadius: 25,
    },
    logo: {
        width: 150,
        height: 150,
        marginVertical: 20,
    },
    footer: {
        width: "100%",
    },
    footerItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 15,
        borderColor: mainColor,
        borderBottomWidth: 1,
        paddingVertical: 7,
    },
    paragraph: {
        width: "100%",
        fontSize: 14,
        lineHeight: 23,
    },
    safe: {
        flex: 1,
        backgroundColor: "#f7fbfc",
    },
    header: {
        width: "100%",
        flexDirection: "row",
        fontWeight: "bold",
        borderColor: mainColor,
        borderLeftWidth: 5,
        paddingLeft: 5,
        marginVertical: 5,
    },
    detail: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        flexWrap: "wrap",
    },
    detailItem: {
        width: "47%",
        flexDirection: "column",
        marginBottom: 10,
    },
})